export const ROLES = {

    CUSTOMER: "CUSTOMER",

    SHOP_OWNER: "SHOP_OWNER",

    DELIVERY_PARTNER: "DELIVERY_PARTNER",

    ADMIN: "ADMIN",

    SUPER_ADMIN: "SUPER_ADMIN"

};

export const PERMISSIONS = {

    MANAGE_PRODUCTS: "MANAGE_PRODUCTS",

    MANAGE_ORDERS: "MANAGE_ORDERS",

    MANAGE_USERS: "MANAGE_USERS",

    MANAGE_PAYMENTS: "MANAGE_PAYMENTS",

    VIEW_ANALYTICS: "VIEW_ANALYTICS",

    MANAGE_SETTINGS: "MANAGE_SETTINGS"

};
