export const TRANSACTION_TYPES = {
  CREDIT: "credit",
  DEBIT: "debit",
};

export const TRANSACTION_CATEGORIES = {
  ORDER_PAYMENT: "ORDER_PAYMENT",
  CASHBACK_EARNED: "CASHBACK_EARNED",
  MONEY_ADDED: "MONEY_ADDED",
  REFERRAL_BONUS: "REFERRAL_BONUS",
  MEMBERSHIP_FEE: "MEMBERSHIP_FEE",
  REFUND: "REFUND",
  REWARD_REDEEMED: "REWARD_REDEEMED",
};
